name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Laravel 10
          # - php: 8.1
            # laravel: 10.*
            # testbench: ^8.0
          - php: 8.2
            laravel: 10.*
            testbench: ^8.0
          - php: 8.3
            laravel: 10.*
            testbench: ^8.0

          # Laravel 11
          # - php: 8.1
            # laravel: 11.*
            # testbench: ^9.0
          - php: 8.2
            laravel: 11.*
            testbench: ^9.0
          - php: 8.3
            laravel: 11.*
            testbench: ^9.0

          # Laravel 12 (PHP >= 8.2)
          - php: 8.2
            laravel: 12.*
            testbench: ^10.0
          - php: 8.3
            laravel: 12.*
            testbench: ^10.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, sqlite, pdo_sqlite, bcmath
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" "illuminate/database:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit --testdox
